"""California CSLB (Contractors State License Board) source.

Two ways to get data:

1. ``CslbScraper`` — drives the public "Check a License" zip-code search at
   https://www.cslb.ca.gov/onlineservices/checklicenseII/zipcodesearch.aspx
   one zip at a time, then fetches each license's detail page for the
   business phone, classification, and personnel (owner / qualifier) names.
   The site is classic ASP.NET WebForms, so each POST must echo back the
   ``__VIEWSTATE`` / ``__EVENTVALIDATION`` tokens from the prior GET.
   CSLB occasionally reshuffles control IDs — the parsers below are
   label/regex driven to survive cosmetic changes, but if the site is
   redesigned, update ``parse_search_results`` / ``parse_license_detail``.

2. ``load_cslb_export`` — imports a CSV generated by CSLB's own Public Data
   Portal (https://www.cslb.ca.gov/onlineservices/dataportal/), which lets
   you build a list by county + classification and download it.  This is
   the fastest, most robust route and puts zero scraping load on the site;
   prefer it when you can click through the portal once.
"""

from __future__ import annotations

import csv
import logging
import re
from typing import Iterable, Iterator

from bs4 import BeautifulSoup

from ..http import PoliteSession
from ..models import Lead, clean_text, normalize_phone
from ..regions import Region
from ..trades import Trade

log = logging.getLogger(__name__)

BASE = "https://www.cslb.ca.gov/onlineservices/checklicenseII"
ZIP_SEARCH_URL = f"{BASE}/zipcodesearch.aspx"
DETAIL_URL = f"{BASE}/licensedetail.aspx"

_LICENSE_LINK = re.compile(r"LicNum=(\d+)", re.IGNORECASE)
_PHONE = re.compile(r"\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}")
_CLASS_CODE = re.compile(r"\b([A-D]-?\d{1,2}|[AB])\b")


def parse_form_state(html: str) -> dict[str, str]:
    """Extract the hidden ASP.NET postback fields from a WebForms page."""
    soup = BeautifulSoup(html, "html.parser")
    state = {}
    for name in ("__VIEWSTATE", "__VIEWSTATEGENERATOR", "__EVENTVALIDATION"):
        node = soup.find("input", attrs={"name": name})
        if node and node.get("value") is not None:
            state[name] = node["value"]
    return state


def parse_search_results(html: str) -> list[dict]:
    """Parse the zip search results into
    ``[{"license_number", "business_name", "classifications"}]``.

    Rows are located by their link to ``LicenseDetail.aspx?LicNum=...`` so
    the parser doesn't depend on table/control IDs.
    """
    soup = BeautifulSoup(html, "html.parser")
    results, seen = [], set()
    for link in soup.find_all("a", href=_LICENSE_LINK):
        lic = _LICENSE_LINK.search(link["href"]).group(1)
        if lic in seen:
            continue
        seen.add(lic)
        row = link.find_parent("tr")
        cells = [clean_text(td.get_text(" ")) for td in
                 (row.find_all("td") if row else [])]
        business_name = ""
        classifications = ""
        for cell in cells:
            if not cell or cell == lic:
                continue
            if _CLASS_CODE.fullmatch(cell) or (
                len(cell) <= 40 and _CLASS_CODE.search(cell)
                and not any(ch.islower() for ch in cell)
            ):
                classifications = f"{classifications} {cell}".strip()
            elif not business_name:
                business_name = cell
        if not business_name:
            business_name = clean_text(link.get_text(" "))
            if business_name == lic:
                business_name = ""
        results.append({
            "license_number": lic,
            "business_name": business_name,
            "classifications": classifications,
        })
    return results


def _value_after_label(soup: BeautifulSoup, *labels: str) -> str:
    """Find the text that follows a bold/label element containing one of
    ``labels`` (case-insensitive)."""
    pattern = re.compile("|".join(re.escape(l) for l in labels), re.I)
    node = soup.find(string=pattern)
    while node is not None:
        parent = node.find_parent(["td", "span", "div", "li", "p"])
        if parent:
            text = clean_text(parent.get_text(" "))
            text = pattern.sub("", text, count=1).strip(" : ")
            if text:
                return text
            sibling = parent.find_next_sibling(["td", "span", "div"])
            if sibling:
                return clean_text(sibling.get_text(" "))
        node = node.find_next(string=pattern)
    return ""


def parse_license_detail(html: str) -> dict:
    """Parse a LicenseDetail.aspx page.

    Returns business_name, phone, city, classifications (list of
    'C36 - Plumbing' style strings) and personnel (list of
    {'name', 'title'}).
    """
    soup = BeautifulSoup(html, "html.parser")
    page_text = soup.get_text(" ")

    business_name = _value_after_label(soup, "Business Name")
    if not business_name:
        h = soup.find(["h1", "h2"], string=lambda s: s and s.strip())
        business_name = clean_text(h.get_text()) if h else ""

    phone = ""
    phone_label = _value_after_label(
        soup, "Business Phone Number", "Business Phone", "Phone Number")
    m = _PHONE.search(phone_label) or _PHONE.search(page_text)
    if m:
        phone = m.group(0)

    address = _value_after_label(soup, "Business Address", "Address")
    city = ""
    m = re.search(r"([A-Za-z .'-]+),?\s+CA\s+\d{5}", address or page_text)
    if m:
        # CSLB renders "123 MISSION ST SAN FRANCISCO, CA 94110" with no
        # comma after the street, so drop everything up to the last street
        # suffix / unit token.
        candidate = clean_text(m.group(1))
        candidate = re.split(
            r"\b(?:ST|AVE|AVENUE|BLVD|RD|ROAD|DR|DRIVE|WAY|CT|COURT|LN|LANE"
            r"|PL|PKWY|HWY|CIR|TER|STE|SUITE|UNIT|#\w+|APT)\b\.?",
            candidate, flags=re.I,
        )[-1]
        city = clean_text(candidate).title()

    classifications = []
    for m in re.finditer(
        r"\b([A-D]-?\d{1,2}|[AB])\s*[-–]\s*([A-Z][A-Za-z,&/ ()-]{3,60})",
        page_text,
    ):
        entry = f"{m.group(1).replace('-', '')} - {clean_text(m.group(2))}"
        if entry not in classifications:
            classifications.append(entry)

    personnel = []
    for row in soup.find_all("tr"):
        cells = [clean_text(td.get_text(" ")) for td in row.find_all("td")]
        if len(cells) < 2:
            continue
        name, title = cells[0], " ".join(cells[1:])
        if re.search(
            r"\b(OWNER|PARTNER|QUALIF|RMO|RME|PRESIDENT|CEO|MEMBER|MANAGER)",
            title, re.I,
        ) and re.search(r"[A-Za-z]{2,}", name):
            personnel.append({"name": name, "title": title})

    return {
        "business_name": business_name,
        "phone": normalize_phone(phone),
        "city": city,
        "classifications": classifications,
        "personnel": personnel,
    }


def pick_owner_name(personnel: list[dict]) -> str:
    """Best available human contact: owner > qualifier/RMO > first listed."""
    priorities = ("OWNER", "PARTNER", "QUALIF", "RMO", "RME", "PRESIDENT",
                  "CEO", "MEMBER", "MANAGER")
    for wanted in priorities:
        for person in personnel:
            if wanted in person.get("title", "").upper():
                return person["name"]
    return personnel[0]["name"] if personnel else ""


class CslbScraper:
    def __init__(self, session: PoliteSession | None = None) -> None:
        self.http = session or PoliteSession(min_delay_seconds=2.0)

    def search_zip(self, zip_code: str, cslb_class: str) -> list[dict]:
        """Run one zip + classification search, following ASP.NET postback."""
        landing = self.http.get(ZIP_SEARCH_URL)
        form = parse_form_state(landing.text)
        soup = BeautifulSoup(landing.text, "html.parser")

        def field(fragment: str, fallback: str) -> str:
            node = soup.find("input", attrs={"name": re.compile(fragment, re.I)}) \
                or soup.find("select", attrs={"name": re.compile(fragment, re.I)})
            return node["name"] if node else fallback

        form[field("zip", "ctl00$MainContent$ZipCodeNumber")] = zip_code
        form[field("classif", "ctl00$MainContent$ClassificationList")] = cslb_class
        submit = soup.find("input", attrs={
            "type": "submit", "name": re.compile("search|submit", re.I)})
        form[submit["name"] if submit else "ctl00$MainContent$SearchButton"] = \
            submit.get("value", "Search") if submit else "Search"

        resp = self.http.post(ZIP_SEARCH_URL, data=form)
        return parse_search_results(resp.text)

    def fetch_detail(self, license_number: str) -> dict:
        resp = self.http.get(DETAIL_URL, params={"LicNum": license_number})
        return parse_license_detail(resp.text)

    def leads(
        self,
        region: Region,
        trade: Trade,
        limit: int | None = None,
        max_zips: int | None = None,
    ) -> Iterator[Lead]:
        assert region.state == "CA", "CSLB only covers California"
        count = 0
        zips = region.zip_codes[:max_zips] if max_zips else region.zip_codes
        seen_licenses: set[str] = set()
        for zip_code in zips:
            try:
                rows = self.search_zip(zip_code, trade.cslb_class)
            except Exception as exc:  # keep going; one bad zip shouldn't kill the run
                log.warning("CSLB zip %s failed: %s", zip_code, exc)
                continue
            log.info("CSLB %s %s: %d licenses in zip %s",
                     trade.cslb_class, region.key, len(rows), zip_code)
            for row in rows:
                lic = row["license_number"]
                if lic in seen_licenses:
                    continue
                seen_licenses.add(lic)
                try:
                    detail = self.fetch_detail(lic)
                except Exception as exc:
                    log.warning("CSLB detail %s failed: %s", lic, exc)
                    continue
                yield Lead(
                    name=pick_owner_name(detail["personnel"]),
                    phone=detail["phone"],
                    business_type=trade.label,
                    location=f"{detail['city'] or zip_code}, CA",
                    business_name=detail["business_name"] or row["business_name"],
                    license_number=lic,
                    source="cslb",
                    state="CA",
                )
                count += 1
                if limit and count >= limit:
                    return


# --- Public Data Portal CSV import ------------------------------------------

_EXPORT_COLUMN_ALIASES = {
    "business_name": ("businessname", "business name", "bus_name", "name"),
    "phone": ("businessphone", "business phone", "phone", "phone number",
              "busphone"),
    "city": ("city", "buscity", "business city"),
    "zip": ("zip", "zipcode", "zip code", "buszip"),
    "license_number": ("licenseno", "license number", "licno", "license #",
                       "licensenumber"),
    "classifications": ("classifications", "classification",
                        "classifications(s)", "class"),
    "owner": ("ownername", "owner name", "personnel", "qualifier",
              "qualifiername"),
}


def _map_columns(header: list[str]) -> dict[str, str]:
    normalized = {re.sub(r"[^a-z#()]", "", h.lower()): h for h in header}
    mapping = {}
    for field_name, aliases in _EXPORT_COLUMN_ALIASES.items():
        for alias in aliases:
            key = re.sub(r"[^a-z#()]", "", alias)
            if key in normalized:
                mapping[field_name] = normalized[key]
                break
    return mapping


def load_cslb_export(
    path: str,
    trades: Iterable[Trade],
    region: Region,
) -> Iterator[Lead]:
    """Import a CSLB Public Data Portal CSV export, keeping rows whose
    classification matches one of ``trades`` and whose zip/city falls in
    ``region``."""
    trades = list(trades)
    region_zips = set(region.zip_codes)
    with open(path, newline="", encoding="utf-8-sig") as fh:
        reader = csv.DictReader(fh)
        cols = _map_columns(reader.fieldnames or [])
        if "business_name" not in cols:
            raise ValueError(
                f"Unrecognized CSLB export header: {reader.fieldnames}")
        for row in reader:
            classifications = row.get(cols.get("classifications", ""), "") or ""
            trade = next(
                (t for t in trades
                 if re.search(rf"\b{t.cslb_class[0]}-?{t.cslb_class[1:]}\b",
                              classifications)),
                None,
            )
            if trade is None:
                continue
            zip_code = clean_text(row.get(cols.get("zip", ""), ""))[:5]
            city = clean_text(row.get(cols.get("city", ""), ""))
            if region_zips and zip_code and zip_code not in region_zips \
                    and not region.matches_city(city):
                continue
            yield Lead(
                name=clean_text(row.get(cols.get("owner", ""), "")),
                phone=row.get(cols.get("phone", ""), ""),
                business_type=trade.label,
                location=f"{city.title() or zip_code}, CA",
                business_name=row.get(cols["business_name"], ""),
                license_number=row.get(cols.get("license_number", ""), ""),
                source="cslb-export",
                state="CA",
            )
